services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=me
      - POSTGRES_DB=census_db

